config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends


  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'home/about' 

 


  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show 
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    if @friend.save
      redirect_to @friend, notice: "Friend was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    if @friend.update(friend_params)
      redirect_to @friend, notice: "Friend was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    redirect_to friends_url, notice: "Friend was successfully deleted."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end


  def about 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 

  <div class = "field form-group mb-3" >
    <%= form.text_field :first_name, class: "form-control", placeholder: "First Name" %>
  </div>

  <div class = "field form-group mb-3" >
    <%= form.text_field :last_name, class: "form-control "  , placeholder: "Last Name" %>
  </div>

  <div class = "field form-group mb-3" >
    <%= form.text_field :email, class: "form-control ", placeholder: "Email" %>
  </div>

  <div class = "field form-group mb-3" >

    <%= form.text_field :phone , class: "form-control " , placeholder: "Phone"  %>
  </div>

  <div class = "field form-group mb-3" >

    <%= form.text_field :twitter, class: "form-control", placeholder: "Twitter" %>
  </div>
  <br/>
<div>
  <%= form.submit class:"btn btn-success" %>
</div>

<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">

<div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold"> 
    <%= friend.first_name %> 
    <%= friend.last_name %>

        
        </h1>
        <p class="col-md-8 fs-4">  
    <strong>Email:</strong>
    <%= friend.email %>  
    <br/> 
    <strong>Phone:</strong>
    <%= friend.phone %>  
    <br/> 
    <strong>Twitter:</strong>
    <%= friend.twitter %>
    </div>



  

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class: "btn btn-secondary" %> 
  <%= link_to "Back to friends", friends_path, class: "btn btn-dark" %><div>  </div>
</div>

app/views/friends/index.html.erb
<h1>Friends</h1> 

<div id="friends"> 
  <table class="table table-bordered table-striped">
      <tr class = "table-dark" > 
        <th scope="col">#</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email </th>
        <th scope="col">Phone </th> 
        <th scope="col">Twitter </th> 
        <th scope="col"> </th>  
        <th scope="col"> </th> 
        <th scope="col"> </th> 
      </tr>
    </thead>
    <tbody>
      <% @friends.each do |friend| %>
        <tr>  
          <td><%= friend.id %></td>
          <td><%= friend.first_name %></td>
          <td><%= friend.last_name %></td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td> 
          <td><%= link_to "Show friend", friend_path(friend), class: 'btn btn-info' %></td>
          <td> <%= link_to "Edit this friend", edit_friend_path(friend), class: 'btn btn-secondary' %> </td>
          <td> <%= link_to "Delete this friend",  @friend, method: :delete, class: 'btn btn-danger' %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


<%= link_to "New friend", new_friend_path, class: "btn btn-secondary" %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<%= render @friend %>

<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend), class: "btn btn-secondary mb-2" %> 
  <%= link_to "Back to friends", friends_path, class: "btn btn-dark mb-2" %>  
  <%= button_to "Delete this friend", @friend, method: :delete, class:"btn btn-danger" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-sm bg-dark w-100">
  <div class="container-sm"> 
    <%= link_to "Friend App", root_path, class: "navbar-brand text-white" %> 
    <%# <a class="navbar-brand" href="#">Friend App</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 m-2">

        <li class="nav-item"> 
            <%= link_to "About Us", home_about_path, class: "nav-link text-light"  %>
        </li>

        <li class="nav-item"> 
            <%= link_to "Friends", friends_path, class: "nav-link text-light"  %>
        </li> 

        <li class="nav-item"> 
            <%= link_to "Register", new_user_registration_path, class: "nav-link text-light"  %>
        </li> 


        <li class="nav-item"> 
            <%= link_to "Log In", new_user_session_path, class: "nav-link text-light"  %>
        </li>


        <li class="nav-item"> 
            <%= link_to "Edit Profile",  edit_user_registration_path, class: "nav-link text-light"  %>
        </li>

         <li class="nav-item sign-out"> 
            <%= link_to "Sign Out",  destroy_user_session_path, method: :delete,  class: "nav-link text-light"  %>
        </li>


      </ul>.
      
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> About us </h1>

app/views/home/index.html.erb
<h1> Hello World </h1> 
This is my first Rails Webpage

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
<%= notice  %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <head>
    <title>Friend App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body id = "body" >
  <%=render 'home/header' %>
  <br/>
  <div class ="container"> 
<% if notice %>
  <%=render 'layouts/alerts' %>
<% end %>

    <%= yield %> 
 </div>
 
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

  </body>
</html>